source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :test do
  gem "rake"
  gem "rspec"
  gem "beaker"
  gem 'beaker-rspec'
  gem "puppet", ENV['PUPPET_GEM_VERSION'] || '> 4.0.0'
  gem "rspec-puppet"
  gem "rspec-puppet-facts"
  gem 'jimdo-rspec-puppet-helpers'
  gem "semantic_puppet"
  # gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppet-check"
  gem "puppetlabs_spec_helper"
end

group :system_tests do
  gem "beaker-rspec"
  gem "beaker-puppet_install_helper"
end
