#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
# metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
mod 'abstractit-puppet', '2.4.0'
mod 'puppet-mcollective', '2.5.0'
mod 'puppetlabs-puppetdb', '5.1.2'
mod 'AlexCline-fstab', '0.5.4'
mod 'puppetlabs-ntp', '<4.2.0'
mod 'saz-rsyslog', '5.0.0'
mod 'derdanne-nfs', '2.0.4'
# A module from git
mod "puppetlabs-rancher",
	:git => 'https://github.com/puppetlabs/puppetlabs-rancher.git'
# mod 'puppet-gluster',
#   :git => 'https://github.com/voxpupuli/puppet-gluster.git'
# mod 'puppet-glusterfs',
#   :git => 'https://github.com/thias/puppet-glusterfs.git'
