#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
# metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
# mod 'puppetlabs-apt', '4.1.0'
mod 'saz-rsyslog', '5.0.0'
# mod 'puppet-nginx', '0.6.0'
# mod 'saz-sudo', '4.1.0'
mod 'puppetlabs-ntp', '<4.2.0'
mod 'puppet-gluster',
  :git => 'https://github.com/voxpupuli/puppet-gluster.git'
mod 'puppet-glusterfs',
  :git => 'https://github.com/thias/puppet-glusterfs.git'
# A module from git
mod "puppetlabs-rancher",
	:git => 'https://github.com/puppetlabs/puppetlabs-rancher.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
