
Vagrant.configure("2") do |config|
  config.vm.box = 'bento/ubuntu-16.04'
  config.vm.hostname = "my-bento.box"

  config.vm.provision "puppet" do |puppet|
  puppet.manifest_file = "site.pp"
end

  config.vm.provider :libvirt do |domain|
    domain.memory = "1024"
    domain.cpus = 2
    domain.nested = true
    domain.driver = "kvm"
    domain.random :model => 'random'
    domain.features = ['acpi', 'apic', 'pae' ]
    domain.storage :file, :device => :cdrom, :dev => 'hdc', :path => '/home/tomasz/VBoxGuestAdditions.iso'
  end

  config.vm.provider :virtualbox do |domain|
    domain.customize ["modifyvm", :id, "--ioapic", "on"]
  end

end
